apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
spec:
  containers:
  - name: test
    image: registry.access.redhat.com/ubi9/ubi
    command: ["/bin/bash","-c","sleep infinity"]
    volumeMounts:
    - mountPath: /data
      name: nfs
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: test-pvc
