apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  namespace: nfs-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
      - name: nfs-client-provisioner
        image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
        env:
        - name: PROVISIONER_NAME
          value: example.com/nfs
        - name: NFS_SERVER
          value: 192.168.100.117
        - name: NFS_PATH
          value: /srv/nfs/kubedata
        volumeMounts:
        - name: nfs
          mountPath: /persistentvolumes
      volumes:
      - name: nfs
        nfs:
          server: 192.168.100.117
          path: /srv/nfs/kubedata
